# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'EnjoyUniversity' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 4.4'
  pod 'Kingfisher'
  pod 'YYModel'
  pod 'JPush', '3.0.5'
  pod ‘UMengUShare/UI’
  pod ‘UMengUShare/Social/ReducedWeChat'
  pod ‘UMengUShare/Social/ReducedQQ'
  pod ‘UMengUShare/Social/ReducedSina'

  # Pods for EnjoyUniversity

  target 'EnjoyUniversityTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EnjoyUniversityUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
